apiVersion: 1

datasources:
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo:3200
      access: proxy
      isDefault: false
      jsonData:
          httpMethod: GET
          tracesToLogsV2:
              datasourceUid: loki
              filterByTraceID: true
              filterBySpanID: false
              customQuery: false
          tracesToMetrics:
              datasourceUid: prometheus
              queries:
                  - name: Request Rate
                    query: 'rate(http_requests_total{service="$__tags{service.name}"}[5m])'
          serviceMap:
              datasourceUid: prometheus
          nodeGraph:
              enabled: true
          search:
              hide: false
          lokiSearch:
              datasourceUid: loki
